
eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

    
        - id: Cart-Services
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v2/**
#      


#app:
#  name: Tech Interface - Swagger and Profiles Tutorial
#server:
#  port: 8091      